spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/comeWithMe
    username: sa
    password:
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.sql: debug
    root: info
server:
  port: 8080
google:
  clientKey: 536517162633-ir2houlr1f6h0ojvtngk1j8ch516cvfo.apps.googleusercontent.com